version: "3"
services:
  gravityWeb:
    image: docker.creativecollisionstech.com/cct/opensource/gravity
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3001:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/gravity/auth:/gravity/auth
      - /srv/gravity/data:/gravity/data
      - /srv/gravity/data/upload:/gravity/public/upload
      - /srv/gravity/security:/gravity/security





