#!/bin/sh

### BEGIN INIT INFO
# Provides:          Gravity Web System
# Required-Start:    docker
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description:	Starts the Gravity Web Docker Image
### END INIT INFO

USR_BIN_DOCKER=/usr/bin/docker
DOCKER_COMPOSE=/usr/local/bin/docker-compose
YML_FILE=/usr/local/gravity/gravity-compose.yml
#GRAVITY_LOG=/usr/local/gravity/logs/gravity.log
GRAVITY_LOG=/dev/null

if [ ! -x $DOCKER_COMPOSE ]; then echo "Couldn't find $DOCKER_COMPOSE"; exit -1; fi
if [ ! -f $YML_FILE ]; then echo "Couldn't find $YML_FILE"; exit -1; fi;

case "$1" in
	start)
		echo "Starting Docker registry"
		$USR_BIN_DOCKER container prune -f
		$DOCKER_COMPOSE -f $YML_FILE up --force-recreate -d >> $GRAVITY_LOG 2>&1 &
	;;
	stop)
		echo "Stopping Docker registry"
		$DOCKER_COMPOSE -f $YML_FILE down >> $GRAVITY_LOG 2>&1 &
		$USR_BIN_DOCKER container prune -f
	;;
	restart)
		$0 stop
		$0 start
	;;
	*)
	log_action_msg "Usage: /etc/init.d/gravity {start|stop|restart}" || grue
	exit 1
	;;
esac

