#!/bin/sh

### BEGIN INIT INFO
# Provides:          gravity
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gravity Web Framework daemon
# Description:       Gravity Web Framework Daemon
### END INIT INFO

# gravity: start/stop script for Gravity Web Framework daemon
# Copyright 2019 Creative Collisions Tech, LLC - Patrick Farrell

PID_FILE=/var/run/gravity.pid
BIN_DIRECTORY=/home/pi/bin

do_stop () {
    if [ -s $PID_FILE ]; then
	pid=`cat ${PID_FILE}`
	kill $pid
	rm -f ${PID_FILE}
	echo "Stopped gravity ($pid)"
    else
	echo "Couldn't stop gravity (not running?)"
    fi
}

do_start () {
    if [ -s $PID_FILE ]; then
	pid=`cat ${PID_FILE}`
	echo "Already running ($pid)"
    elif [ -f $PYTHON_FILE ]; then
	$BIN_DIRECTORY/gravity > /dev/null 2>&1 &
	pid=$!
	echo $pid > $PID_FILE
	echo "Started gravity ($pid)"
    else
	echo "ERROR: couldn't find Python file $PYTHON_FILE"
	exit 4
    fi
}

case "$1" in
    start)
	do_start
	;;
    restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
    stop)
	do_stop
	;;
    *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
